import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "You Can WIN",
    author: "Shiv Khera",
    price: "5000",
    quantity: "5",
    id: 1,
    categoryName: "non-fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "You are Winner",
    author: "Junaid Qureshi",
    price: "3000",
    quantity: 6,
    id: 2,
    categoryName: "horror",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 3,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 4,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 5,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 6,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 7,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 8,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 9,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 10,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 11,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 12,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 13,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 14,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 15,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 16,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 17,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 18,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 19,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 20,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 21,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 22,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 23,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 24,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 25,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 26,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 27,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 28,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 29,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 30,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 31,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 32,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 33,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 34,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 35,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 36,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 37,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 38,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 39,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 40,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 41,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 42,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 43,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 44,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 45,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 46,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 47,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 48,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 49,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    price: "1000",
    quantity: 4,
    id: 50,
    categoryName: "fiction",
    image: "	https://m.media-amazon.com/images/I/41ij2wmfHUL._AC_UY218_.jpg",
  },
];
